development:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: test_development
  username: root
  password:

test:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: test_development
  username: root
  password:

staging:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: test_development
  username: root
  password:  

production:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: test_development
  username: root
  password:
