development:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: test_development
  username: root
  password: 
  host: 127.0.0.1

test:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: test_development
  username: root
  password: 
  host: 127.0.0.1

staging:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: test_development
  username: root
  password: 
  host: 127.0.0.1

production:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: test_development
  username: root
  password: 
  host: 127.0.0.1
